### PR TITLE
refactor existing code with hooks

### PR DESCRIPTION
**Pull request by phaniteja1**
Refactor code with React Hooks

### CODE REVIEW

**Comment by mebble** [comment]
I don't know how to use the Hooks API, so I can't tell what's wrong, but there are errors in the Chrome console on running `npm run dev`:
```
Uncaught TypeError: (0 , _react.useState) is not a function
    at App (app.js:56)
    at mountIndeterminateComponent (react-dom.development.js:8574)
    at beginWork (react-dom.development.js:8978)
    at performUnitOfWork (react-dom.development.js:11814)
    at workLoop (react-dom.development.js:11843)
    at HTMLUnknownElement.callCallback (react-dom.development.js:100)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:138)
    at invokeGuardedCallback (react-dom.development.js:187)
    at replayUnitOfWork (react-dom.development.js:11318)
    at renderRoot (react-dom.development.js:11885)
```
```
The above error occurred in the <App> component:
    in App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
```
```
Uncaught TypeError: (0 , _react.useState) is not a function
    at App (app.js:56)
    at mountIndeterminateComponent (react-dom.development.js:8574)
    at beginWork (react-dom.development.js:8978)
    at performUnitOfWork (react-dom.development.js:11814)
    at workLoop (react-dom.development.js:11843)
    at renderRoot (react-dom.development.js:11874)
    at performWorkOnRoot (react-dom.development.js:12449)
    at performWork (react-dom.development.js:12370)
    at performSyncWork (react-dom.development.js:12347)
    at requestWork (react-dom.development.js:12247)
```

**Comment by phaniteja1** [comment]
@mebble I am unable to see any errors in the console when I run `npm run dev`. Can you please tell me the steps to reproduce it? Thanks!

**Comment by phaniteja1** [comment]
@mebble  I updated the package.json file. Can you please re-install the packages and check if the problem still exists? Thanks!

**Comment by mebble** [comment]
Oh of course. The prior react version didn't support hooks. I'll try it out now

**Pull request merged**
